application: syndicate-manager
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.DS_Store
- ^README\..*
- \.gitignore
- ^\.git/.*

builtins:
- deferred: on
- appstats: on

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

handlers:
  - url: /favicon.ico
    static_files: static/images/favicon.ico
    upload: static/images/favicon.ico
    mime_type: image/x-icon

  - url: /robots.txt
    static_files: static/robots.txt
    upload: static/robots.txt
  
  - url: /js
    static_dir: static/js
  - url: /css
    static_dir: static/css
  - url: /img
    static_dir: static/images
    
  - url: /tasks/.*
    script: cm.main.app
    secure: always
    login: admin
 
  - url: /cron/.*
    script: cm.main.app
    secure: always
    login: admin
    
  - url: /.*
    script: cm.main.application
    secure: always